export const companyTypes = [
  // "Marketing Agency",
  // "IT company",
  // "Recruitment Agency",
  // "Software Company",
  // "Construction Company",
  // "Car Dealer",
  // "Car Rental",
  // "Car Repair",
  // "Car Wash",
  // "Electric Vehicle Charging Station",
  // "Gas Station",
  // "Parking",
  // "Farm",
  // "Art Gallery",
  // "Museum",
  // "Performing Arts Theater",
  // "Library",
  // "Preschool",
  // "Primary School",
  // "Secondary School",
  // "University",
  // "Amusement Center",
  // "Amusement Park",
  // "Aquarium",
  // "Banquet Hall",
  // "Bowling Alley",
  // "Casino",
  // "Community Center",
  // "Convention Center",
  // "Cultural Center",
  // "Dog Park",
  // "Event Venue",
  // "Hiking Area",
  // "Historical Landmark",
  // "Marina",
  // "Movie Theater",
  // "National Park",
  // "Night Club",
  // "Park",
  // "Tourist Attraction",
  // "Visitor Center",
  // "Wedding Venue",
  // "Zoo",
  "Accounting",
  // "ATM",
  // "Bank",
  // "Insurance Agency",
  // "Consultant",
  // "Courier Service",
  // "Lawyer",
  // "Real Estate Agency",
  // "Electrician",
  // "Plumber",
  // "Roofing Contractor",
  // "Cleaning Services",
  // "Security Company",
  // "American Restaurant",
  // "Bakery",
  // "Bar",
  // "Cafe",
  // "Restaurant",
  // "Fast Food Restaurant",
  // "Ice Cream Shop",
  // "Pizza Restaurant",
  // "Seafood Restaurant",
  // "Steak House",
  // "Country",
  // "Locality",
  // "Postal Code",
  // "School District",
  // "City Hall",
  // "Courthouse",
  // "Embassy",
  // "Fire Station",
  // "Local Government Office",
  // "Post Office",
  // "Dental Clinic",
  // "Dentist",
  // "Doctor",
  // "Hospital",
  // "Pharmacy",
  // "Physiotherapist",
  // "Spa",
  // "Bed and Breakfast",
  // "Guest House",
  // "Hotel",
  // "Motel",
  // "Resort Hotel",
  // "Church",
  // "Hindu Temple",
  // "Mosque",
  // "Synagogue",
  // "Barber Shop",
  // "Beauty Salon",
  // "Cemetery",
  // "Florist",
  // "Funeral Home",
  // "Hair Salon",
  // "Laundry",
  // "Locksmith",
  // "Moving Company",
  // "Storage",
  // "Tailor",
  // "Auto Parts Store",
  // "Bicycle Store",
  // "Book Store",
  // "Clothing Store",
  // "Convenience Store",
  // "Electronics Store",
  // "Furniture Store",
  // "Grocery Store",
  // "Home Improvement Store",
  // "Jewelry Store",
  // "Pet Store",
  // "Shopping Mall",
  // "Sporting Goods Store",
  // "Supermarket",
  // "Wholesaler",
  // "Fitness Center",
  // "Golf Course",
  // "Gym",
  // "Sports Club",
  // "Airport",
  // "Bus Station",
  // "Train Station",
  // "Truck Stop",
];

// export const cityNames = [
//   "Mumbai",
//   "Delhi",
//   "Bangalore",
//   "Hyderabad",
//   "Ahmedabad",
//   "Chennai",
//   "Kolkata",
//   "Surat",
//   "Pune",
//   "Jaipur",
//   "Lucknow",
//   "Kanpur",
//   "Nagpur",
//   "Indore",
//   "Thane",
//   "Bhopal",
//   "Visakhapatnam",
//   "Pimpri & Chinchwad",
//   "Patna",
//   "Vadodara",
//   "Ghaziabad",
//   "Ludhiana",
//   "Agra",
//   "Nashik",
//   "Faridabad",
//   "Meerut",
//   "Rajkot",
//   "Kalyan & Dombivali",
//   "Vasai Virar",
//   "Varanasi",
//   "Srinagar",
//   "Aurangabad",
//   "Dhanbad",
//   "Amritsar",
//   "Navi Mumbai",
//   "Allahabad",
//   "Ranchi",
//   "Haora",
//   "Coimbatore",
//   "Jabalpur",
//   "Gwalior",
//   "Vijayawada",
//   "Jodhpur",
//   "Madurai",
//   "Raipur",
//   "Kota",
//   "Guwahati",
//   "Chandigarh",
//   "Solapur",
//   "Hubli and Dharwad",
//   "Bareilly",
//   "Moradabad",
//   "Karnataka",
//   "Gurgaon",
//   "Aligarh",
//   "Jalandhar",
//   "Tiruchirappalli",
//   "Bhubaneswar",
//   "Salem",
//   "Mira and Bhayander",
//   "Thiruvananthapuram",
//   "Bhiwandi",
//   "Saharanpur",
//   "Gorakhpur",
//   "Guntur",
//   "Bikaner",
//   "Amravati",
//   "Noida",
//   "Jamshedpur",
//   "Bhilai Nagar",
//   "Warangal",
//   "Cuttack",
//   "Firozabad",
//   "Kochi",
//   "Bhavnagar",
//   "Dehradun",
//   "Durgapur",
//   "Asansol",
//   "Nanded Waghala",
//   "Kolapur",
//   "Ajmer",
//   "Gulbarga",
//   "Jamnagar",
//   "Ujjain",
//   "Loni",
//   "Siliguri",
//   "Jhansi",
//   "Ulhasnagar",
//   "Nellore",
//   "Jammu",
//   "Sangli Miraj Kupwad",
//   "Belgaum",
//   "Mangalore",
//   "Ambattur",
//   "Tirunelveli",
//   "Malegoan",
//   "Gaya",
//   "Jalgaon",
//   "Udaipur",
//   "Maheshtala",
// ];

export const countryName = "USA";
export const countryCode = "US";
export const cityNames = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Philadelphia",
  "Phoenix",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Jacksonville",
  "Indianapolis",
  "San Francisco",
  "Austin",
  "Columbus",
  "Fort Worth",
  "Charlotte",
  "Detroit",
  "El Paso",
  "Memphis",

  // "Baltimore",
  // "Boston",
  // "Seattle",
  // "Washington",
  // "Nashville-Davidson",
  // "Denver",
  // "Louisville/Jefferson",
  // "Milwaukee",
  // "Portland",
  // "Las Vegas",
  // "Oklahoma City",
  // "Albuquerque",
  // "Tucson",
  // "Fresno",
  // "Sacramento",
  // "Long Beach",
  // "Kansas City",
  // "Mesa",
  // "Virginia Beach",
  // "Atlanta",

  // "Colorado Springs",
  // "Omaha",
  // "Raleigh",
  // "Miami",
  // "Cleveland",
  // "Tulsa",
  // "Oakland",
  // "Minneapolis",
  // "Wichita",
  // "Arlington",
  // "Bakersfield",
  // "New Orleans",
  // "Honolulu",
  // "Anaheim",
  // "Tampa",
  // "Aurora",
  // "Santa Ana",
  // "St. Louis",
  // "Pittsburgh",
  // "Corpus Christi",

  // "Riverside",
  // "Cincinnati",
  // "Lexington-Fayette",
  // "Anchorage",
  // "Stockton",
  // "Toledo",
  // "St. Paul",
  // "Newark",
  // "Greensboro",
  // "Buffalo",
  // "Plano",
  // "Lincoln",
  // "Henderson",
  // "Fort Wayne",
  // "Jersey City",
  // "St. Petersburg",
  // "Chula Vista",
  // "Norfolk",
  // "Orlando",
  // "Chandler",
  
  // "Laredo",
  // "Madison",
  // "Winston-Salem",
  // "Lubbock",
  // "Baton Rouge",
  // "Durham",
  // "Garland",
  // "Glendale",
  // "Reno",
  // "Hialeah",
  // "Chesapeake",
  // "Scottsdale",
  // "North Las Vegas",
  // "Irving",
  // "Fremont",
  // "Irvine",
  // "Birmingham",
  // "Rochester",
  // "San Bernardino",
  // "Spokane",
];

export const userAgentStrings = [
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.2227.0 Safari/537.36",
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.3497.92 Safari/537.36",
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36",
];
